swagger: '2.0'
info:
  title: My API
  description: A simple APIView for demonstrating documentation.
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@yourapi.local
  license:
    name: BSD License
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /api
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /items/:
    get:
      operationId: items_list
      description: Retrieve all items.
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - items
    post:
      operationId: items_create
      description: Create a new item.
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - items
    parameters: []
definitions: {}
