name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate OpenAPI specification
      run: |
        python manage.py generateschema > src/docs/openapi.yaml

    - name: Set up docToolchain
      run: |
        chmod +x dtcw
        ./dtcw install doctoolchain

    - name: Export OpenAPI documentation
      run: ./dtcw exportOpenApi

    - name: Generate documentation
      run: ./dtcw generateHTML

    - name: Move documentation to root of gh-pages folder
      run: |
        mkdir -p out
        cp -r build/html5/arc42/modules/ROOT/pages/* out/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./out
        publish_branch: gh-pages
